export const TOTAL_EXPENSES_MONTH_ACTION_TYPES = {
  UPDATE_TOTAL_EXPENSES_MONTH_ENTRIES: "UPDATE_TOTAL_EXPENSES_MONTH_ENTRIES",
  CLEAR_TOTAL_EXPENSES_MONTH_ENTRIES: "CLEAR_TOTAL_EXPENSES_MONTH_ENTRIES",
};
