export const TOTAL_EXPENSES_WEEK_ACTION_TYPES = {
  UPDATE_TOTAL_EXPENSES_WEEK_ENTRIES: "UPDATE_TOTAL_EXPENSES_WEEK_ENTRIES",
  CLEAR_TOTAL_EXPENSES_WEEK_ENTRIES: "CLEAR_TOTAL_EXPENSES_WEEK_ENTRIES",
};
