export const CUSTOMER_ACTION_TYPES = {
  ADD_SUBSCRIPTION_PRICE: "ADD_SUBSCRIPTION_PRICE",
  ADD_SUBSCRIPTION_DATA: "ADD_SUBSCRIPTION_DATA",
  ADD_CUSTOMER_DETAILS: "ADD_CUSTOMER_DETAILS",
  ADD_CUSTOMER_ID: "ADD_CUSTOMER_ID",
  CLEAR_CUSTOMER_DETAILS: "CLEAR_CUSTOMER_DETAILS",
  CLEAR_SUBSCRIPTION_PRICE: "CLEAR_SUBSCRIPTION_PRICE",
  CLEAR_SUBSCRIPTION_DATA: "CLEAR_SUBSCRIPTION_DATA",
  CLEAR_CUSTOMER_ID: "CLEAR_CUSTOMER_ID",
  UPDATE_SUBSCRIPTION_DATA: "UPDATE_SUBSCRIPTION_DATA",
};
