export const TOTAL_EXPENSES_YEAR_ACTION_TYPES = {
  UPDATE_TOTAL_EXPENSES_YEAR_ENTRIES: "UPDATE_TOTAL_EXPENSES_YEAR_ENTRIES",
  CLEAR_TOTAL_EXPENSES_YEAR_ENTRIES: "CLEAR_TOTAL_EXPENSES_YEAR_ENTRIES",
};
